### ISSUE TITLE
Displaying a multigraph properly

### ISSUE THREAD

**Issue by benedictleejh** [graphstream/gs-core#118]
I'm trying to display a multigraph, but if there are multiple edges leading from one vertex to another, they end up overlapping, and you can't discern the each individual edge. For example in this code:

``` java
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.swingViewer.Viewer;

public class Tutorial1 {
    public static void main(String args[]) {
        Graph graph = new MultiGraph("Test");

        graph.addNode("A");
        graph.addNode("B");

        graph.addEdge("1", "A", "B", true);
        graph.addEdge("2", "A", "B", true);

        Viewer viewer = graph.display();
    }
}
```

The resulting display would only show one edge, because the 2 edges are overlapped.

**Comment by mirkara** [comment]
Using v1.3 I get
ava.lang.ClassNotFoundException: org.graphstream.ui.j2dviewer.J2DGraphRenderer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.graphstream.ui.swingViewer.Viewer.newGraphRenderer(Viewer.java:303)
	at org.graphstream.graph.implementations.DefaultGraph.display(DefaultGraph.java:818)
	at org.graphstream.graph.implementations.DefaultGraph.display(DefaultGraph.java:812)

Any idea why?

**Comment by pigne** [comment]
Get `gs-ui` in in your classpath.

**Comment by mirkara** [comment]
Thanks for the fast response!
I added
```
<dependency>
    <groupId>org.graphstream</groupId>
    <artifactId>gs-ui</artifactId>
    <version>1.1.2</version>
</dependency>
```
but that resulted in 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/graphstream/ui/swingViewer/util/Camera
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.graphstream.ui.view.Viewer.newGraphRenderer(Viewer.java:349)
	at org.graphstream.graph.implementations.AbstractGraph.display(AbstractGraph.java:753)
	at org.graphstream.graph.implementations.AbstractGraph.display(AbstractGraph.java:747)
```

**Comment by mirkara** [comment]
Ok, both are using 1.3.
I get:
```
org.graphstream.ui.view.Viewer newGraphRenderer
WARNING: Cannot create graph renderer.
java.lang.ClassNotFoundException: org.graphstream.ui.j2dviewer.J2DGraphRenderer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.graphstream.ui.view.Viewer.newGraphRenderer(Viewer.java:349)
	at org.graphstream.graph.implementations.AbstractGraph.display(AbstractGraph.java:753)
	at org.graphstream.graph.implementations.AbstractGraph.display(AbstractGraph.java:747)
```
