### ISSUE TITLE
Closing a View with J2DGraphRenderer when view hasn't been shown causes a NullPointerException

### ISSUE THREAD

**Issue by jmcomets** [graphstream/gs-core#150]
I encountered this bug when integrating a few views inside my Swing application. When the view is added to a initially hidden component (for example a JTabbedPane), it needs to be shown at least once before calling `viewer.close()`, otherwise the following NullPointerException is generated.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
   at org.graphstream.ui.graphicGraph.StyleGroup.removeRenderer(StyleGroup.java:594)
   at org.graphstream.ui.j2dviewer.J2DGraphRenderer.removeRenderers(J2DGraphRenderer.scala:166)
   at org.graphstream.ui.j2dviewer.J2DGraphRenderer.close(J2DGraphRenderer.scala:122)
   at org.graphstream.ui.swingViewer.DefaultView.close(DefaultView.java:195)
   at org.graphstream.ui.view.Viewer.close(Viewer.java:304)
   at SSCCE$1.windowClosing(SSCCE.java:45)
   at java.awt.Window.processWindowEvent(Window.java:2051)
   at javax.swing.JFrame.processWindowEvent(JFrame.java:296)
   at java.awt.Window.processEvent(Window.java:2009)
   at java.awt.Component.dispatchEventImpl(Component.java:4861)
   at java.awt.Container.dispatchEventImpl(Container.java:2287)
   at java.awt.Window.dispatchEventImpl(Window.java:2719)
   at java.awt.Component.dispatchEvent(Component.java:4687)
   at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
   at java.awt.EventQueue.access$200(EventQueue.java:103)
   at java.awt.EventQueue$3.run(EventQueue.java:694)
   at java.awt.EventQueue$3.run(EventQueue.java:692)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
   at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
   at java.awt.EventQueue$4.run(EventQueue.java:708)
   at java.awt.EventQueue$4.run(EventQueue.java:706)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
   at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
   at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
   at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
   at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
   at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
   at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

Below is a SSCCE. Notice that when you select the "Second" tab before closing the window, the program exits normally.

```java
import org.graphstream.algorithm.generator.Generator;
import org.graphstream.algorithm.generator.RandomGenerator;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swingViewer.ViewPanel;
import org.graphstream.ui.view.Viewer;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class SSCCE implements Runnable {
    public static void main(String[] args) {
        System.setProperty("org.graphstream.ui.renderer", "org.graphstream.ui.j2dviewer.J2DGraphRenderer");
        SwingUtilities.invokeLater(new SSCCE());
    }

    @Override
    public void run() {
        // create graph
        Graph graph = new SingleGraph("Random");
        Generator gen = new RandomGenerator(2);
        gen.addSink(graph);
        gen.begin();
        for (int i = 0; i < 100; i++)
        {
            gen.nextEvents();
        }
        gen.end();

        // create viewer
        final Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        viewer.setCloseFramePolicy(Viewer.CloseFramePolicy.CLOSE_VIEWER);
        ViewPanel view = viewer.addDefaultView(false);

        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                viewer.close();
            }
        });
        JTabbedPane tabbedPane = new JTabbedPane();
        tabbedPane.addTab("First", new JPanel());
        tabbedPane.addTab("Second", view);
        frame.add(tabbedPane);
        frame.pack();
        frame.setVisible(true);
    }
}
```

**Comment by jansvajcr** [comment]
Does a workaround exist at least?

**Comment by jmcomets** [comment]
Looking at #160, it seems that this issue was probably already fixed. I don't have the means to check this so I can't say for sure.

**Comment by kitskub** [comment]
This has not been fixed yet.
