### ISSUE TITLE
(Regression) since 1.3, DefaultView stops working as soon as it’s resized below a certain dimension

### ISSUE THREAD

**Issue by spider-mario** [graphstream/gs-core#155]
The following code works with GraphStream 1.2, regardless of the size of the window:

```java
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swingViewer.Viewer;

import javax.swing.*;

public class ViewBug {
    public static void main(String... arguments) {
        SwingUtilities.invokeLater(() -> {
            Graph g = new SingleGraph("graph1");
            g.addNode("node1").setAttribute("label", "Node 1");
            g.addNode("node2").setAttribute("label", "Node 2");
            g.addEdge("edge1", "node1", "node2");

            Viewer viewer = new Viewer(g, Viewer.ThreadingModel.GRAPH_IN_SWING_THREAD);
            viewer.enableAutoLayout();
            viewer.addDefaultView(true);
        });
    }
}
```

But if one upgrades to GraphStream 1.3 (which requires changing the third import to `org.graphstream.ui.view.Viewer` and `GRAPH_IN_SWING_THREAD` to `GRAPH_IN_GUI_THREAD`):

```java
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;

import javax.swing.*;

public class ViewBug {
    public static void main(String... arguments) {
        SwingUtilities.invokeLater(() -> {
            Graph g = new SingleGraph("graph1");
            g.addNode("node1").setAttribute("label", "Node 1");
            g.addNode("node2").setAttribute("label", "Node 2");
            g.addEdge("edge1", "node1", "node2");

            Viewer viewer = new Viewer(g, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
            viewer.enableAutoLayout();
            viewer.addDefaultView(true);
        });
    }
}
```

and resizes the window below a certain size, then the graph is not rendered anymore (even after giving the window its original size back) and the error stream is flooded with the following stack trace:

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: DefaultCamera.pushView() / popView() wrongly nested
	at org.graphstream.ui.swingViewer.util.DefaultCamera.pushView(DefaultCamera.java:494)
	at org.graphstream.ui.swingViewer.basicRenderer.SwingBasicGraphRenderer.renderGraph(SwingBasicGraphRenderer.java:214)
	at org.graphstream.ui.swingViewer.basicRenderer.SwingBasicGraphRenderer.render(SwingBasicGraphRenderer.java:166)
	at org.graphstream.ui.swingViewer.DefaultView.render(DefaultView.java:239)
	at org.graphstream.ui.swingViewer.DefaultView.paintComponent(DefaultView.java:174)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5226)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:290)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1265)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1973)
	at java.awt.Window.paint(Window.java:3912)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:835)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:807)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:807)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:782)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:731)
	at javax.swing.RepaintManager.access$1300(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1720)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by spider-mario** [comment]
According to `git bisect`:

~~~
a8ecae0a7285c08fda42c4cf371fdbcbf58fa431 is the first bad commit
commit a8ecae0a7285c08fda42c4cf371fdbcbf58fa431
Author: Antoine <antoine.dutot@gmail.com>
Date:   Fri Jun 6 10:16:15 2014 +0200

    Added ComponentListener to DefaultView

:040000 040000 b9b179622e7bd9aebeea99d59631a4096d43cc2f fb4b4404b6d6417de97bab857569ab79c225c5f2 M      src
~~~

**Comment by gsavin** [comment]
Problem comes when frame dimensions are less than the padding size, so aspect ratio value becomes negative. It was not handle before, but we just add an exception throwing with the last 1.3.
Now, the view computes a new aspect ratio, reducing the padding size (only if needed).

Sorry for the late reply.
