### ISSUE TITLE
Exception after many iterations of updating edge attributes

### ISSUE THREAD

**Issue by sfwd** [graphstream/gs-core#179]
Exception in thread "Thread-22" java.lang.NullPointerException
        at org.graphstream.stream.SourceBase.manageEvents(SourceBase.java:872)
        at org.graphstream.stream.SourceBase.sendAttributeChangedEvent(SourceBase.java:810)
        at org.graphstream.util.GraphListeners.sendAttributeChangedEvent(GraphListeners.java:73)
        at org.graphstream.graph.implementations.AbstractNode.attributeChanged(AbstractNode.java:94)
        at org.graphstream.graph.implementations.AbstractElement.addAttribute(AbstractElement.java:544)
        at org.graphstream.graph.implementations.AbstractElement.setAttribute(AbstractElement.java:560)
        at sai.Observer.run(Observer.java:128)
        at java.lang.Thread.run(Thread.java:745)

**Comment by sfwd** [comment]
And this is an abbreviation of the call that I'm using to set edge attributes:
```
graph.getEdge("edge").setAttribute("ui.color",0.5);
```

**Comment by pigne** [comment]
Could you provide a reproducible example?
