### ISSUE TITLE
Nesting a ViewPanel into a JPanel doesn't work

### ISSUE THREAD

**Issue by mibadim** [graphstream/gs-core#189]
I hope I got this right. Since `org.graphstream.ui.swingViewer.ViewPanel` inherits from JPanel, it should be easy to add it to an instance of the latter.

```Java
import javax.swing.JFrame;
import javax.swing.JPanel;

import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swingViewer.ViewPanel;
import org.graphstream.ui.view.Viewer;

public class GSTester {

	public static void main(String[] args) {
		Graph g = new SingleGraph("a");
		g.addNode("a");
		g.addNode("b");
		g.addEdge("ab", "a", "b");
		
		Viewer viewer = new Viewer(g,
				Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
		JFrame frame = new JFrame("Graph");
		frame.setSize(300, 200);		
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		JPanel panel = new JPanel();
		ViewPanel view = viewer.addDefaultView(false);
		panel.add(view);

		frame.add(panel);
		frame.setVisible(true);
	}
}
```
It doesn't work. I get loads of exceptions.

```
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: ratio PX to G
U cannot be negative (-25,000000)
	at org.graphstream.ui.swingViewer.util.GraphMetrics.setRatioPx2Gu(GraphMetrics.
java:345)
	at org.graphstream.ui.swingViewer.util.DefaultCamera.autoFitView(DefaultCamera.
java:561)
	at org.graphstream.ui.swingViewer.util.DefaultCamera.pushView(DefaultCamera.jav
a:487)
	at org.graphstream.ui.swingViewer.basicRenderer.SwingBasicGraphRenderer.renderG
raph(SwingBasicGraphRenderer.java:214)
	at org.graphstream.ui.swingViewer.basicRenderer.SwingBasicGraphRenderer.render(
SwingBasicGraphRenderer.java:166)
	at org.graphstream.ui.swingViewer.DefaultView.render(DefaultView.java:239)
	at org.graphstream.ui.swingViewer.DefaultView.paintComponent(DefaultView.java:1
74)
	at javax.swing.JComponent.paint(JComponent.java:1046)
	at javax.swing.JComponent.paintChildren(JComponent.java:879)
	at javax.swing.JComponent.paint(JComponent.java:1055)
	at javax.swing.JComponent.paintChildren(JComponent.java:879)
	at javax.swing.JComponent.paint(JComponent.java:1055)
	at javax.swing.JComponent.paintChildren(JComponent.java:879)
	at javax.swing.JComponent.paint(JComponent.java:1055)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:585)
	at javax.swing.JComponent.paintChildren(JComponent.java:879)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5230)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java
:295)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1249)
	at javax.swing.JComponent.paint(JComponent.java:1032)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.awt.Container.paint(Container.java:1967)
	at java.awt.Window.paint(Window.java:3877)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:819)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:796)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivileg
e(ProtectionDomain.java:77)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:796)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:769)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:718)
	at javax.swing.RepaintManager.access$1100(RepaintManager.java:62)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1677)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivileg
e(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java
:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:16
1)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java
:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```
What's wrong here?

**Comment by gsavin** [comment]
You do not set a prefered size to your panel, so it has a (0, 0) size...
We added some code to handle this zero-size more silently, but users still have to set the size of their components.

**Comment by mibadim** [comment]
So I tried this:
```
panel.setPreferredSize(new Dimension(200, 150));
```
With numerous values—no chance. BTW: As far as I know, the size of a JPanel is controlled by the parent's LayoutManager, not by itself.

**Comment by gsavin** [comment]
That's correct. And since default layout manager of `JPanel` is a `FlowLayout`, the layout will size the components to... their preferred size.

It did not work with your example because you are setting the size of the container of the view, not the size of the view itself. And you should not add directly components to your `JFrame`, but to the content pane of the frame.

Hope it helps...

**Comment by mibadim** [comment]
OK, thank you, that worked. But is there also a way to set relative sizes? Absolute values may be a bad idea sometimes.

**Comment by gsavin** [comment]
Of course, as in any Swing application. You can try to use a `BorderLayout`, putting the view at the center of it. But using the `JFrame.pack()` may cause to come back to the preferred size of the components, as said in the documentation :

> public void pack()
   Causes this Window to be sized to fit the preferred size and layouts of its subcomponents. The resulting width and height of the window are automatically enlarged if either of dimensions is less than the minimum size as specified by the previous call to the setMinimumSize method.

**Comment by mibadim** [comment]
Using a BorderLayout works. Thanks a lot.
