### ISSUE TITLE
NullPointerException without message

### ISSUE THREAD

**Issue by vishrantgupta** [graphstream/gs-core#279]
I am getting following exception, Graphstream version: 1.3

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.graphstream.ui.j2dviewer.Camera.nodeContains(Camera.scala:568)
        at org.graphstream.ui.j2dviewer.Camera$$anonfun$findNodeOrSpriteAt$1.apply(Camera.scala:200)
        at org.graphstream.ui.j2dviewer.Camera$$anonfun$findNodeOrSpriteAt$1.apply(Camera.scala:197)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at org.graphstream.ui.j2dviewer.Camera.findNodeOrSpriteAt(Camera.scala:197)
        at org.graphstream.ui.j2dviewer.J2DGraphRenderer.findNodeOrSpriteAt(J2DGraphRenderer.scala:135)
        at org.graphstream.ui.swingViewer.DefaultView.findNodeOrSpriteAt(DefaultView.java:335)
        at org.graphstream.ui.view.util.DefaultMouseManager.mousePressed(DefaultMouseManager.java:132)

```

Environment:
```
PS C:\WINDOWS\system32> java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

**Comment by hichbra** [comment]
Hi ! Can you share your code ?

**Comment by vishrantgupta** [comment]
Hi @hichbra 

Below is the code snippet:

```
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.ui.view.util.DefaultMouseManager;

public class CustomMouseManager extends DefaultMouseManager {


    @Override
    public void mouseDragged(MouseEvent event) {
        // just override super class method to block node dragging
    }

    @Override
    public void mousePressed(MouseEvent event) {
LINE 84:   super.mousePressed(event);
        ...
    }

}
```

















```

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.graphstream.ui.j2dviewer.Camera.nodeContains(Camera.scala:568)
        at org.graphstream.ui.j2dviewer.Camera$$anonfun$findNodeOrSpriteAt$1.apply(Camera.scala:200)
        at org.graphstream.ui.j2dviewer.Camera$$anonfun$findNodeOrSpriteAt$1.apply(Camera.scala:197)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at org.graphstream.ui.j2dviewer.Camera.findNodeOrSpriteAt(Camera.scala:197)
        at org.graphstream.ui.j2dviewer.J2DGraphRenderer.findNodeOrSpriteAt(J2DGraphRenderer.scala:135)
        at org.graphstream.ui.swingViewer.DefaultView.findNodeOrSpriteAt(DefaultView.java:335)
        at org.graphstream.ui.view.util.DefaultMouseManager.mousePressed(DefaultMouseManager.java:132)

        at mypackage.name.graph.visualization.CustomMouseManager.mousePressed(CustomMouseManager.java:84)

        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6586)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6354)
        at java.desktop/java.awt.Container.processEvent(Container.java:2260)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2318)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4906)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2304)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by hichbra** [comment]
Did you correctly initialize your manager ?

**Comment by vishrantgupta** [comment]
@hichbra yes I have initialized it, in Java <8 it works fine.

**Comment by hichbra** [comment]
Can you share the part of code where you initialized your manager and the part where you use it ?
