### ISSUE TITLE
Betweeness Centrality not working for my graph

### ISSUE THREAD

**Issue by akankshachandel** [graphstream/gs-core#295]
Hello,

I am using graphstream to calculate page rank and betweeness  centrality of my graph with around 641 vertex and 2342 edges. The compute function is giving me following error:
Exception in thread "main" java.lang.NullPointerException
at org.graphstream.algorithm.BetweennessCentrality.centrality(BetweennessCentrality.java:609) at org.graphstream.algorithm.BetweennessCentrality.betweennessCentrality(BetweennessCentrality.java:358) at  org.graphstream.algorithm.BetweennessCentrality.compute(BetweennessCentrality.java:323)

while it is working fine for the example program for small graph given in the documentation at the graphstream website.
Please help at your earliest convenience, my problem is kind of time sensitive.

**Comment by hichbra** [comment]
Hi,
I can't reproduce the error it's work fine for me, do you have a code we could use ?
