### ISSUE TITLE
Problem importing GraphML without edge label

### ISSUE THREAD

**Issue by robinschmid** [graphstream/gs-core#303]
Hey all,

great work. I really like this library. 

Now I wanted to import some data from GraphML format. The FileSourceFactory gave me a null (as my file extension was .graphml and not .xml). After using the direct FileSourceGraphML class, I was able to import the nodes but it fails to import the edges as it is missing an id column. Why don't we just compile missing ids as a combination of the source and target

    <edge source="7107" target="7107">
      <data key="d43">7107</data>
      <data key="d44">1.0</data>
      <data key="d45">Cosine</data>

Cheers
Robin

java.io.IOException: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[14498,39]
Message: edge must have an id
	at org.graphstream.stream.file.FileSourceGraphML.nextEvents(FileSourceGraphML.java:326)
	at org.graphstream.stream.file.FileSourceGraphML.readAll(FileSourceGraphML.java:276)
	at org.graphstream.stream.file.FileSourceGraphML.readAll(FileSourceGraphML.java:248)
	at net.sf.mzmine.modules.visualization.metamsecorrelate.visual.sub.networks.externalsource.ExternalSourceNetworkPanel.createNewGraph(ExternalSourceNetworkPanel.java:40)
	at net.sf.mzmine.modules.visualization.metamsecorrelate.visual.sub.networks.externalsource.ExternalSourceNetworkPanel.<init>(ExternalSourceNetworkPanel.java:24)
	at net.sf.mzmine.modules.visualization.metamsecorrelate.visual.sub.networks.externalsource.ExternalSourceNetworkPanel.<init>(ExternalSourceNetworkPanel.java:18)
	at net.sf.mzmine.modules.visualization.metamsecorrelate.visual.sub.networks.externalsource.ExternalSourceNetworkFrame.<init>(ExternalSourceNetworkFrame.java:20)
	at net.sf.mzmine.modules.visualization.metamsecorrelate.visual.sub.networks.externalsource.ExternalSourceNetworkFrame.main(ExternalSourceNetworkFrame.java:10)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[14498,39]
Message: edge must have an id
	at org.graphstream.stream.file.FileSourceGraphML.newParseError(FileSourceGraphML.java:365)
	at org.graphstream.stream.file.FileSourceGraphML.__edge(FileSourceGraphML.java:1309)
	at org.graphstream.stream.file.FileSourceGraphML.__graph(FileSourceGraphML.java:1126)
	at org.graphstream.stream.file.FileSourceGraphML.__graphml(FileSourceGraphML.java:591)
	at org.graphstream.stream.file.FileSourceGraphML.nextEvents(FileSourceGraphML.java:324)
	... 7 more

**Comment by robinschmid** [comment]
Ok I just forked the source and you already added this change. DO you have any plans to push the latest version to maven central?
https://mvnrepository.com/artifact/org.graphstream/gs-core

Thanks you very much.

**Comment by hichbra** [comment]
They are some features and fixes directly put in the 2.0 version.
From version 2.0, we use [jitpack](https://jitpack.io/) that allow to include a github repository as a library. Because it's more convenient for us. For the moment I don't know if we will add them in the central after the beta test.
