### ISSUE TITLE
Problems in creating custom graph with custom node and edge

### ISSUE THREAD

**Issue by kenchiu21** [graphstream/gs-core#310]
Hi all,  I am currently using the alpha release of gs-core and gs-ui-fx. 
I am trying to create my own type of graph called StateGraph by extending the MultiGraph class.
The type of node in this class are called State, which extends MultiNode. I am also trying to create my own kind of Edge called StateGraphEdge by extending AbstractEdge. However, I faced 2 problems:

Problem 1: Is there away to add edge to the graph dynamically by first creating an Edge object and called method like graph.add(edge) other than the default method Graph.addEdge(String id, Node node1, Node node2)?

Problem 2: The class StateGraph has a method getEquivalentState(), which check if state with same URL and HTM DOM exists.  However, a ClassCastException is thrown whether method is called. I would like to ask is there away to alleviate this problem. Is there any possible way to alleviate this probelm. I would be grateful there is a way to creating custom graph with custom node and edge correctly.

 The code and the exception is attached below:

Code:
public class StateGraph extends MultiGraph {
	private State root;
	private StateIdFactory stateIdFactory;
	private EdgeIdFactory edgeIdFactory;
        //some methods

	public State getEquivalentState(URL url, Document htmlDom) {
		State equivalentState = null;
		Iterator<Node> iterator = this.iterator();
		while (iterator.hasNext()) {
			State state = (State) iterator.next();
			if (state.isEquivalent(url, htmlDom)) {
				equivalentState = state;
				break;
			}
		}
		return equivalentState;
	}
}

public class State extends MultiNode{
	private URL url;
	private Document htmlDom;
       //some  methods
}

public class StateGraphEdge extends AbstractEdge{

	protected StateGraphEdge(String id, AbstractNode source, AbstractNode target) {
		super(id, source, target, true);
	}

	private ArrayList<Action> actionList;

	public ArrayList<Action> getActionList() {
		return actionList;
	}

	public void setActionList(ArrayList<Action> actionList) {
		this.actionList = actionList;
	}
	
}

Exception:
java.lang.ClassCastException: class org.graphstream.graph.implementations.MultiNode cannot be cast to class com.awtu.biz.graph.State (org.graphstream.graph.implementations.MultiNode and com.awtu.biz.graph.State are in unnamed module of loader 'app')
	at com.awtu.biz.graph.StateGraph.getEquivalentState(StateGraph.java:66)
	at com.awtu.biz.test.scripted.ScriptedTestRunner.runTestCase(ScriptedTestRunner.java:82)
	at com.awtu.biz.test.scripted.ScriptedTestRunner.runTestSuite(ScriptedTestRunner.java:50)
	at com.awtu.biz.test.scripted.ScriptedTestRunner.runTestSuite(ScriptedTestRunner.java:38)
	at com.awtu.app.controller.ScriptedTestRunController$1.call(ScriptedTestRunController.java:32)
	at com.awtu.app.controller.ScriptedTestRunController$1.call(ScriptedTestRunController.java:1)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kenchiu21** [comment]
By the way, I have seen a post in StackOverFlow whicih mentioned the use of  setNodeFactory

https://stackoverflow.com/questions/49980954/how-to-store-data-in-graphs-using-inheritance-with-graphstream

**Comment by pigne** [comment]
The `setNodeFactory` seems indeed to be missing in you code. The SO post you reffer to should help you fix your problem.

**Comment by kenchiu21** [comment]
@pigne Thank you so much, it does not throw the ClassCastException now. However, when i tried to do State state = (State) iterator.next();
The the state attributes of the node returned by iterator.next() are null, and a ClassNotLoadedException is observed. When i run the program in debug mode, the attribute of the State i created is not null, but it becomes null when i cast Node into State.

**Comment by kenchiu21** [comment]
Thank you so much, some how i have solved the problem by using to HasMap to keep track on nodes and edges, and create iterator from the entry set to loop all nodes. Should there be any better way to achieve looping all node, please do not hesitate to let me know. Many mant thanks.

this.stateMap = new HashMap<String, State>();
Iterator<Entry<String, State>> iterator = this.stateMap.entrySet().iterator();
